### ISSUE TITLE
同じ人が「いいね」を付箋に何回もできないようにしたい。なぜなら、いいねの数と人数が一致しているとの認識してしまうから。 

### ISSUE THREAD

**Issue by miyukin** [wakurun-yd/wakurun-yd#18]
受入条件
・いいねの数と人数が一致していること。

**Comment by Peranikov** [comment]
どうするかな～

**Comment by nanakira** [comment]
ログインの仕組みを入れたら解決すると思いますけど、わざわざログインして使ってもらえるか？というあたりが心配ですね。
気軽さが失われる気がするので。

**Comment by Peranikov** [comment]
雑にやろうと思えば、SessionかCookieに「このボードのこの付箋にいいね!したよ」という情報を持たせておけば出来そうではありますけどね。
(もちろん、SessionとCookieが消えれば再度いいねできる)

**Comment by nanakira** [comment]
ですね。
やるならそっちかなと思ってました（POが許容するなら）

**Comment by Peranikov** [comment]
むしろ永遠にいいね!できるという仕様にしよう（POが許容するなら）

**Comment by nanakira** [comment]
はてなの Fav-star とかたくさん出来るので、アリっちゃアリだと思いますね。
（今のアイコンだと Facebook を想像すると思いますが）
