### ISSUE TITLE
参加者として対象（今日）のKPTボードに「いいね」を押すことが出来る。それは、参加者同士共感したいためだ。

### ISSUE THREAD

**Issue by miyukin** [wakurun-yd/wakurun-yd#7]
# 完了条件
- 共感できる仕組みがあること。

**Comment by nanakira** [comment]
「いいね」の対象はふせんではなくボードでしょうか？

**Comment by miyukin** [comment]
ふせんをイメージしてました。ボードだとどんなイメージになるのでしょうか？

**Comment by nanakira** [comment]
自分もふせんだと思ったんですが、「KPTボードに「いいね」を押すことが出来る」記載だったので念の為確認でした。ふせんでいいと思います :smiley:

**Comment by nanakira** [comment]
1枚のふせんには1人1回かぎり「いいね」できる制限が必要でしょうか？
もし必要だと、ユーザーアカウント管理が必要になるので見積もり大きくなると思います。
ふせんごとの単なるカウンタとしての実装なら見積もり小さくなります。

**Comment by miyukifuji** [comment]
確認ありがとうございます。単なるカウントでOKです。

**Comment by Peranikov** [comment]
miyukinが二人になった...(しかもうさぎと豚)

**Comment by Peranikov** [comment]
Railsで「いいね!」を実装する方法としてactiverecord-reputation-systemというGemがあるにはあるんですが、機能過多で冗長なので自前で実装したほうが良いかもしれないです。

http://easyramble.com/activerecord-reputation-system.html

**Comment by Peranikov** [comment]
あと、一々リロードしたくないのでajax絡みますね。拙作のPuhaar!も同じようにしています(最近更新してないなぁ...)

**Comment by Peranikov** [comment]
あとは @nanakira と同意。
